terraform/api.tf
=> Update schema version to 0.1.0

bootstrap.md
=> Move bootstrap.md to the root directory

terraform/domain.tf, terraform/girder.tf
Repoint girder and gui to www.dandiarchive.org.
=> Point resources to www during maintenance window

terraform/api.tf, terraform/staging_pipeline.tf, terraform/variables.tf
This should follow https://github.com/dandi/dandi-api/pull/272
=> Remove environment vars for integration with Girder 3

terraform/domain.tf
This addresses [this comment](https://github.com/dandi/dandi-infrastructure/pull/74#discussion_r651852240) from the previous PR.
=> Remove incorrect subdomain from "name"

terraform/api.tf, terraform/staging_pipeline.tf
This makes it easier to override in the future.
=> Add an explicit value for django_default_from_email

terraform/api.tf
=> Bump production schema version to 0.4.4

terraform/api.tf, terraform/staging_pipeline.tf, terraform/variables.tf
I've updated the password secret in Terraform Cloud.
=> Use the official datacite credentials

terraform/api.tf
Addresses https://github.com/dandi/dandi-api/issues/256.
attn: @satra
=> Allow CORS access from codepen.io

terraform/staging_pipeline.tf
This will bump the row limit from 1e4 to 1e7.
=> Upgrade postgres from hobby-dev to hobby-basic

terraform/api.tf
draft pending staging testing of #85
=> Bump schema version to 0.5.1

terraform/main.tf, terraform/staging_bucket.tf, terraform/staging_pipeline.tf
* Modify the ownership rules so that they are identical to production
* Add a logging bucket (just like in production)
=> Make staging bucket identical to production

terraform/sponsored_bucket.tf
Same reasoning as #96 , but for production.
=> Allow S3 deletes

terraform/api.tf, terraform/staging_pipeline.tf
Adds new environment variables introduced by https://github.com/dandi/dandi-api/pull/613 to the terraform config.
=> Add domain environment variables required by API server

terraform/zarr_experiment.tf
This is a temporary application that I will use to quickly iterate on zarr upload code without totally breaking staging.
=> Add zarr experiment app to Heroku

terraform/benchmark_server.tf
If we're doing more benchmarking, we're going to be uploading lots of junk files, so I'm standing up a new temporary deployment to keep the mess isolated.
=> Add benchmark deployment

terraform/api.tf
Support for https://github.com/dandi/dandi-archive/pull/1018
=> Add DJANGO_DANDI_JUPYTERHUB_URL env var

terraform/domain.tf, terraform/redirector.tf, terraform/staging_pipeline.tf
Required for https://github.com/dandi/dandi-archive/issues/1025
=> Update Route53 records to reorganize domains

terraform/api.tf, terraform/staging_pipeline.tf
Related to https://github.com/dandi/dandi-archive/issues/985
=> Remove manifest worker

.gitignore
See https://github.com/github/gitignore/blob/main/Terraform.gitignore.
=> Add gitignore from terraform template

terraform/modules/dandiset_bucket/main.tf
This doesn't change any resources, the plan should be a noop. This allows us to use more advanced features like dynamic blocks.
=> Convert json policies to data documents

terraform/staging_bucket.tf
=> Remove migrated moved blocks

terraform/api.tf, terraform/modules/dandiset_bucket/main.tf, terraform/modules/dandiset_bucket/variables.tf, terraform/sponsored_bucket.tf, terraform/sponsored_iam.tf
Sibling PR to #140, fixes #107.
=> Refactor sponsored bucket to use bucket module

terraform/api.tf, terraform/sponsored_bucket.tf
These changes have already been applied, so this is a clean plan.
=> Remove moved blocks

terraform/modules/dandiset_bucket/main.tf
See https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html for more details.
=> Remove ACL configuration from log buckets

terraform/modules/dandiset_bucket/main.tf
This should facilitate scripted updates of https://github.com/dandi/dandi-archive/pull/1570.
=> Add cross account log bucket access

terraform/api.tf, terraform/staging_pipeline.tf
Related to https://github.com/dandi/dandi-archive/issues/1424 and https://github.com/dandi/dandi-archive/issues/1605. This adds a worker dyno for processing s3 log files with a concurrency of 1.
=> Add analytics worker dyno

terraform/staging_pipeline.tf
This is just reconciling the terraform code with the true state of things.
=> Fix dyno size of api_staging_analytics_worker

.github/workflows/ci.yml, terraform/modules/dandiset_bucket/variables.tf
=> Add CI for terraform linting/validation

terraform/webdav.tf
=> Deploy `dandidav` service to Heroku

terraform/api.tf
This is to help alleviate issues with increased web traffic
=> Increase quantity of web dynos to 3

terraform/modules/dandiset_bucket/main.tf
This PR adds a policy which will block access to any objects in the S3 bucket which have the `embargoed=true` tag applied to them. It does this with two conditions:
1. That the object have the `embargoed=true` tag applied to it.
2. That the Arn of the user requesting access is not equal to the heroku user arn (so that the API can still access that object regardless).
According to [these](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-logic-multiple-context-keys-or-values.html) docs, multiple conditions at the top level will act as a logical AND, so this should behave the way we expect.
I've tested this policy and can confirm if the tag is applied, access is denied to everyone except for the user specified in the policy. If the tag is removed, the object is …
=> Add embargoed tags bucket policy

terraform/staging_pipeline.tf, terraform/webdav.tf
These look like changes that were made outside of terraform recently, this should reconcile them with terraform state.
=> Update terraform to reflect correct heroku state

terraform/imports.tf
This has been applied (#187) and can now be removed.
=> Remove import block

terraform/api.tf, terraform/staging_pipeline.tf
See https://github.com/kitware-resonant/terraform-heroku-resonant
@brianhelba
=> Upgrade Terraform module for Resonant

terraform/api.tf, terraform/staging_pipeline.tf
For the neurosift app to write back to the server for metadata changes. see: https://github.com/flatironinstitute/neurosift/discussions/215
cc: @magland
=> Add CORS support for neurosift

terraform/modules/dandiset_bucket/main.tf
This is (hopefully the final) follow up to #199 and #204. Fixes #192 
There can be only be one `aws_s3_bucket_lifecycle_configuration` resource per bucket. That _configuration_  can contain multiple _rules_, but you can't have multiple _configurations_ for one S3 bucket. In practice, defining two in Terraform caused the first configuration to be removed. (see screenshot)
See Terraform docs (first "Note" on that page)
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_lifecycle_configuration
=> Consolidate `aws_s3_bucket_lifecycle_configuration` resources into one

terraform/domain.tf
Paired with https://github.com/dandi/upptime/pull/263.
cc @yarikoptic
=> Add DNS record for upptime's `status` subdomain

terraform/domain.tf
These changes have been manually added to Route 53.
cc @bendichter
=> Add Bluesky DNS record

terraform/email_forwarding.tf
This depends on #211 being merged, planned, and applied successfully.
=> Remove import statements from ImprovMX configuration

terraform/staging_pipeline.tf
https://github.com/dandi/dandi-archive/issues/1030
=> Remove gui-staging URL from CORS whitelist

terraform/modules/dandiset_bucket/main.tf
Reverts dandi/dandi-infrastructure#240
The application is still attempting to set ACLs, which is causing failures.
=> Revert "Disable ACLs on the S3 bucket and require object ownership"
