dandi/dandi-infrastructure

- terraform/api.tf
After switching to the production bucket, any S3 operations return:
```
Mar 29 18:04:00 dandi-api app/web.1                     botocore.exceptions.ClientError: An error                   
Mar 29 18:04:00 dandi-api app/web.1                     occurred (AccessDenied) when calling the                    
Mar 29 18:04:00 dandi-api app/web.1                     PutObject operation: Access Denied                          
```
This reverts that switch so that the app is still usable while we diagnose.
> Revert switch to the production bucket

- terraform/api.tf
- terraform/sponsored_bucket.tf
Give the Heroku IAM user permission to write to the sponsored bucket directly using policies rather than delegating through roles.
I think roles will not cut it for giving the Heroku user access to the sponsored bucket, as they need to be explicitly activated and require a role session.
> Sponsored bucket permissions

- terraform/sponsored_bucket.tf
* Enforce `bucket-owner-full-control` is present on all uploaded objects
* Turn on the Bucket Owner Preferred option for object ownership on the
bucket. Any objects with `bucket-owner-full-control` specified will have
their ownership transferred to the bucket, so the bucket's policies will
apply to them.
> Require bucket-owner-full-control and claim ownership

- terraform/staging_pipeline.tf
The Heroku AWS staging user was set up with a permission that allowed it
access to the staging bucket, but the staging bucket was not set up to
allow access to the user. This adds the correct policies to the bucket.
> Allow AWS staging user to write to staging bucket

- terraform/api.tf
This is no longer needed, now that the sponsored bucket is being used.
>  Remove the "dandi-api-dandisets-testing" bucket

- terraform/api.tf
This provides us 550 MB/day of log transfer, up from the current limit
of 250 MB/day.
> Upgrade papertrail to "volmar" plan

- terraform/staging_pipeline.tf
It's exceeding CloudAMQP resource quotas and throwing continual errors.
> Disable the staging app

- terraform/api.tf
- terraform/staging_pipeline.tf
Otherwise, both deployments report errors as "production" by default, which is incorrect for the staging deployment.
> Specify the Sentry environment for each deployment

- terraform/domain.tf
The MX records to add were taken from the ImprovMX console, after I set up (on their end) email forwarding from `[info|help]@dandiarchive.org` to `dandi@mit.edu`.
> Add MX records to enable email forwarding via ImprovMX

- terraform/staging_pipeline.tf
I think this was neglected when setting up the alternative Oauth application for staging.
> Use the alternative settings class in staging

- terraform/api.tf
@waxlamp - unfortunately the cors request is being made from `https://cdpn.io`, so this has to be updated to include that domain.
> add codepen domain

- terraform/api.tf
- terraform/staging_pipeline.tf
When DJANGO_DANDI_DOI_PUBLISH is set to "true", DOIs generated during
publish have status "findable", which means they cannot be deleted. We
only want that in production.
Takes advantage of https://github.com/dandi/dandi-api/pull/451
> Set DJANGO_DANDI_DOI_PUBLISH in production/staging

- terraform/api.tf
so https://bioimagesuiteweb.github.io/webapp/viewer.html?image=https://api.dandiarchive.org/api/assets/d62f3ac5-2a0f-4170-a2d9-37d9bb2085c0/download/ works (datasets 26, 58, 66 have .nii.gz files)
ref: https://github.com/dandi/dandi-api/issues/256
> Add bisweb to CORS whitelist

- terraform/api.tf
There is now a signal handler that allows read only CORS requests from
any origin, so these explicit exceptions are no longer required.
Fixes #91
> Remove codepen.io and bioimagesuiteweb.github.io from allowed CORS origins

- terraform/api.tf
- terraform/staging_pipeline.tf
This is now set in the dandi-api settings.py, so we do not need to set
it in Terraform.
See https://github.com/dandi/dandi-api/pull/494
> Do not set DJANGO_DANDI_SCHEMA_VERSION

- terraform/domain.tf
This record is recommended by the ImprovMX setup procedures, which we are using for managing dandiarchive.org email addresses.
> Add an SPF record for email handling

- terraform/staging_bucket.tf
The existing policy effectively only grants Put* permissions, since it
requires `X-Amz-ACL: bucket-owner-full-control`, which is not set for
Delete* operations.
> Add policy to allow S3 deletes

- terraform/staging_pipeline.tf
This reverts commit 89b4925a48d1c279befa0bffed30f35e1706337e.
And also explicitly sets `heroku_web_dyno_size` and `heroku_worker_dyno_size` to `hobby`.
> Revert "Upgrade staging temporarily"

- terraform/api.tf
I noticed the `DJANGO_CONFIGURATION` environment variable is set for the staging server https://github.com/dandi/dandi-infrastructure/blob/master/terraform/staging_pipeline.tf#L27 but not for production (it is set in heroku though, presumably someone set it manually there).
> Add missing env var to terraform config

- terraform/modules/dandiset_bucket/main.tf
- terraform/modules/dandiset_bucket/variables.tf
- terraform/sponsored_bucket.tf
- terraform/staging_bucket.tf
I made a mistake in #105 and passed an ARN where the module expected a username.
> Fix user argument for dandiset bucket module

- terraform/modules/dandiset_bucket/main.tf
The header setting X-Amz-ACL=bucket-owner-full-control is only
meaningful on "Put" operations. We were requiring it for all operations,
which meant that read operations were not allowed, as they did not
include it.
Fixes https://github.com/dandi/dandi-archive/issues/809
> Allow Get, List, and Delete without ACL

- terraform/api.tf
- terraform/staging_pipeline.tf
We recently moved Netlify deploy previews to the staging Netlify "app", so they now live at `https://deploy-preview-*--gui-staging-dandiarchive-org.netlify.app/`  instead of `https://deploy-preview-*--gui-dandiarchive-org.netlify.app/`. This PR updates the CORS whitelist for the staging server with this new URL format.
I also removed the `https://gui-beta-dandiarchive-org.netlify.app` URL from the production server CORS whitelist. It doesn't point to anything, and I suspect it's just an outdated URL that was never removed from the terraform config - @waxlamp @dchiquito @AlmightyYakob does anyone remember what this URL was used for, and can confirm that it's okay to remove?
> Update CORS whitelists

- terraform/modules/dandiset_bucket/main.tf
Currently, the dandiset_bucket module is only used for embargo buckets.
The production embargo bucket isn't working because the Heroku IAM user
is in a different account than the embargo bucket.
Add a new bucket policy to the staging and production buckets that
explicitly allow the IAM user to do anything to the bucket. Cross
account access requires that both the IAM user and the bucket have a
policy allowing access.
To resolve the issue and verify that this is the correct solution, I manually put this policy onto the production embargo bucket:
```json
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "Statement1",
"Effect": "Allow",
"Principal": {
"AWS": "arn:aws:iam::278212569472:user/dandi-api-heroku"
},
"Action": "s3:*",
"Resource": [
"arn:aws:s3:::dandiarchive-embargo/*", …
```
> Add bucket policy to dandiset_bucket module

- terraform/api.tf
The Heroku web dyno is currently set to 2X in Heroku, but 1X in the Terraform config. The dyno was scaled up to 2X by hand a while back, but that change was never encoded in Terraform.
> Change `heroku_web_dyno_size` to standard-2x

- terraform/api.tf
We've switched to Sassy-Squirel-1 tier for CloudAMQP, but the Terraform code wasn't updated accordingly.
> Update CloudAMQP plan in Terraform

- terraform/api.tf
- terraform/staging_pipeline.tf
Our Heroku configuration has drifted away from our Terraform state. This PR updates our Terraform code to represent the current state of Heroku; in other words, this should be a no-op when applied and will only affect the state file on TF Cloud.
> Update Terraform values to be consistent with Heroku web console

- terraform/modules/dandiset_bucket/main.tf
- terraform/sponsored_bucket.tf
- terraform/staging_bucket.tf
- terraform/staging_pipeline.tf
This brings our state back to parity with production:
- Codifies the encryption status of the buckets
- Upgrades the cloudamqp plan (a manual rm/import was done locally)
> Bring terraform state up to date

- terraform/modules/dandiset_bucket/main.tf
- terraform/modules/dandiset_bucket/variables.tf
- terraform/staging_bucket.tf
- terraform/staging_pipeline.tf
This is the first of a couple PRs I'd like to make around refactoring our S3 infrastructure. I tried to make the plan as minimal as possible by using the `moved` blocks but there's still a small portion that couldn't be covered. Namely, the heroku user is getting some permissions through an IAM policy that it used to have through a bucket policy. This refactor gives slightly *more* permissions than necessary to the heroku user for the ease of refactoring these parts. Once everything uses the common module then we can be judicious about principle of least privilege (ideally this would be data driven via #131).
@mvandenburgh I double checked this but since everything we're doing here will eventually be applied to the sponsored bucket I'd like you to take a careful look at it and let me know …
> Refactor staging bucket to use bucket module

- terraform/modules/dandiset_bucket/main.tf
- terraform/modules/dandiset_bucket/variables.tf
- terraform/sponsored_bucket.tf
This was just put in place to make the diffs a bit easier to read, but now we can remove it which will trigger a delete/recreate of the policy.
> Remove policy name variable

- .github/workflows/auto-add-issues.yml
This should cause new issues filed here to show up in our project board.
Note that this is an identical copy of the same workflow file in dandi-archive. After brief reading about using an org-level .github repository, I'm not sure that's the right way to share this workflow between repos (unless we do that and then use "caller" workflows in each repository--that would be better than this straight copying, I guess).
I'd like to merge this in so we can have the auto-add functionality, then revisit later to refactor the workflow out into a common space, if possible. If there's a simple way to accomplish that right away, let me know and we can maybe do that instead.
TODO:
> Add action to auto-add new issues to project board

- terraform/staging_pipeline.tf
Our monthly billing cycle has rolled over for our staging CloudAMQP plan, so we can restore it back to the cheaper tier now.
> Restore old CloudAMQP tier for staging

- terraform/modules/dandiset_bucket/main.tf
The GUI seems to indicate `ListBucket` is the bucket policy permission, even though `ListObjectsV2` is the IAM version of the policy :-/.
> Use ListBucket permission

- terraform/modules/dandiset_bucket/log_bucket.tf
- terraform/modules/dandiset_bucket/main.tf
This is a minor refactor of the `dandiset_bucket` module that moves all resources related to the logging bucket to a separate file to make it easier to parse what's going on without confusing the two buckets.
Note this does split an IAM User policy into two separate policies, so merging and applying this will mutate the infrastructure.
> Move log bucket resources to seperate file

- terraform/api.tf
- terraform/staging_pipeline.tf
Requires #160 to be merged first.
> Upgrade `girder/girder4/heroku` module to latest version

- terraform/modules/dandiset_bucket/main.tf
- terraform/modules/dandiset_bucket/variables.tf
- terraform/sponsored_bucket.tf
- terraform/staging_bucket.tf
Implements this design doc https://github.com/dandi/dandi-archive/pull/1674.
I put this the "trailing delete" setting behind a flag, `trailing_delete`, and only enabled it in staging. Once we are ready to enable this in production, we can remove this flag and have it be the default behavior of the `dandiset_bucket` module.
> Implement trailing delete functionality on staging

- terraform/modules/dandiset_bucket/main.tf
we are trying to see if we can load nwb files remotely and this particular tool first makes a head request: https://github.com/usnistgov/h5wasm/issues/12
this PR allows cross-origin head requests.
> allow HEAD requests from different origins.

- terraform/webdav.tf
Neither of these are needed anymore now that we are deploying by pushing directly to Heroku. See https://github.com/dandi/dandidav/pull/105.
I picked the `heroku-community/cli` because a Heroku app requires at least 1 buildpack to deploy successfully, and it was the closest thing to a "no-op" buildpack officially maintained by Heroku.
> Disable Rust buildpack and dyno-metadata feature

- terraform/domain.tf
This corrects a spurious plan element that seems to show up in every plan, in which the domain for the AWS ACM validation record loses a trailing dot.
The Terraform code indeed does not include the trailing dot, but it seems as though at runtime, the deployed resource somehow gains it, leaving the deployed state inconsistent with the code. I don't know what causes that, but this "fixes" the problem by bringing the code into line with what the deployed resource seems to be.
For an example of a TF plan that includes the spurious change, see https://app.terraform.io/app/dandi/workspaces/dandi-prod/runs/run-VFdyCNW18mBqo6ju.
If there's a better way to solve this, let's close this PR and pursue that solution instead.
Unrelated to the fix, but the plan also includes a change to the dandidav …
> Use a trailing dot for AWS ACM validation record

- terraform/domain.tf
Following on from the drama in #176, this PR attempts to go back to not using the trailing dot for that Route53 CNAME entry so it is in line with the other entries.
We believe this cycle of adding the dot and then removing it will eliminate the hiccup, but we need to observe what happens after this PR is merge in order to make sure.
> Remove trailing dot for ACM CNAME entry

- terraform/domain.tf
Reverts dandi/dandi-infrastructure#178
#178 was an experiment in seeing whether we could have a trailing-dot-free record in Terraform. It did not work, probability due to something we are missing, but inlcuding the trailing dot doesn't harm anything, and in fact reflects the value currently held by Route53.
> Revert "Remove trailing dot for ACM CNAME entry"

- terraform/modules/dandiset_bucket/main.tf
This permission is needed in order to allow the Heroku application to set the `embargoed` tag on embargoed blobs.
> Give Heroku user `s3:PutObjectTagging` permission

- terraform/api.tf
- terraform/staging_pipeline.tf
- terraform/variables.tf
This PR adds a `dev_email` variable that will be passed to django via the `DJANGO_DANDI_DEV_EMAIL` env var. The value for this terraform setting has already been supplied in terraform cloud.
> Specify developer email list as env var

- terraform/modules/dandiset_bucket/main.tf
This gives the production heroku user permission for the `PutObjectTagging` action, from the bucket policy itself. This actually solves the issue that #182 was attempting to solve. That change didn't work because permissions to the production bucket must be added on the bucket policy itself (because the bucket and user reside in two different accounts), and we were only adding that permission to the user itself, not the bucket.
> Add `s3:PutObjectTagging` permission to sponsored bucket

- terraform/aws_oidc.tf
This should allow terraform cloud to authenticate with AWS via a direct trust relationship instead of relying on a manual token placed in the environment of TFC.
See
https://developer.hashicorp.com/terraform/cloud-docs/workspaces/dynamic-provider-credentials#how-dynamic-credentials-work for documentation on how the dynamic credential system works.
This adds the infrastructure for doing this authentication but doesn't switch over to it yet, that can be done after merging.
> Add identity provider for terraform cloud

- terraform/imports.tf
We recently upgraded our Heroku Postgres DB. This involved provisioning a new DB instance, which put our Terraform state out of sync.
This resolves the erroneous plan in #186 which wants to create a new Heroku Postgres addon.
> Import new heroku postgres addon

- terraform/modules/dandiset_bucket/main.tf
Addresses https://github.com/dandi/dandi-infrastructure/pull/186#discussion_r1793671893.
Currently, the trailing delete lifecycle policy applies to the entire bucket. This PR updates it to only apply to the `blobs/` prefix, i.e. the prefix where asset blobs are stored. With this change, other objects in the bucket such as Zarr data and manifest files will not be impacted by the lifecycle policy.
> Scope trailing delete policy to `blobs` prefix only

- terraform/modules/dandiset_bucket/main.tf
- terraform/modules/dandiset_bucket/variables.tf
- terraform/sponsored_bucket.tf
- terraform/staging_bucket.tf
Requirements before merging this PR
> Enable trailing delete in production

- terraform/modules/dandiset_bucket/main.tf
- terraform/modules/dandiset_bucket/variables.tf
- terraform/staging_bucket.tf
Closes #192.
Configures an S3 lifecycle rule to cap the number of noncurrent versions of manifest files to 1. See #192 for the rationale behind this rule.
Note - this only enables it in staging. After merging and verifying that it works correctly, I'll make a follow up PR enabling it for the production bucket.
> Manifest file garbage collection

- terraform/modules/dandiset_bucket/main.tf
Follow up to #199 
[The apply from that PR failed ](https://app.terraform.io/app/dandi/dandi-prod/runs/run-YYwvSw99qE78Vck4) because the `noncurrent_days` field is actually mandatory. The AWS Terraform provider docs are incorrect, see https://github.com/hashicorp/terraform-provider-aws/issues/35328.
The AWS Console UI also confirms this -
> Fix `noncurrent_version_expiration`

- terraform/modules/dandiset_bucket/main.tf
- terraform/modules/dandiset_bucket/variables.tf
- terraform/staging_bucket.tf
Follow up to enable #199 in production.
> Enable manifest garbage collection in prod

- terraform/domain.tf
This depends on #208 being merged, planned, and applied successfully.
> Remove Bluesky DNS record import block

- terraform/domain.tf
This is needed to use [Google search console](https://search.google.com/search-console/about) for purposes such as https://github.com/dandi/dandi-archive/issues/2199.
Note that I made the change to the TXT record manually, and this PR catches the TF state up to the change I made (hence, the plan should show no changes).
> Add google-site-verification proof to TXT record

- terraform/api.tf
- terraform/modules/dandiset_bucket/log_bucket.tf
- terraform/staging_pipeline.tf
With https://github.com/dandi/dandi-archive/pull/2425, we no longer need the extra celery worker or extra IAM policies to grant the Heroku user access to the logging bucket.
> Remove analytics worker + associated IAM policies

- terraform/domain.tf
- terraform/staging_pipeline.tf
https://github.com/dandi/dandi-archive/issues/1030
This is the first in a series of PRs to fully rename the `staging` deployment to `sandbox`. All this does is add a new subdomain/CNAME record, `sandbox.dandiarchive.org`, and points it at `sandbox-dandiarchive-org.netlify.com`
Separately, I've created a new Netlify site for this. It's currently accessible at https://sandbox-dandiarchive-org.netlify.app/, but once this PR is merged and applied it will be https://sandbox.dandiarchive.org. 
Once we've confirmed that the change works as expected, I'll update the old `gui-staging-dandiarchive-org` Netlify site to simply redirect to the sandbox one and then work on switching the API server as well.
> Add `sandbox.dandiarchive.org` subdomain (web client only)

- terraform/api.tf
Our log volume has increased recently, so this bumps us up to the next tier for papertrail.
> Bump Heroku Patertrail tier

- terraform/domain_sandbox.tf
- terraform/staging_pipeline.tf
This is a prerequisite for https://github.com/dandi/dandi-archive/pull/2449. I've created the `api-staging-dandiarchive-org` app on Netlify and pointed it at the `redirector/` directory.
> Configure DNS for netlify api-staging redirector

- terraform/modules/dandiset_bucket/main.tf
Closes #137 
ACLs are deprecated by AWS, in favor of bucket policies.
Additionally, this allows us to set `BucketOwnerEnforced` Object Ownership. Accordingly, ACLs set by by other AWS accounts are ignored, so we no longer have to worry about `bucket-owner-full-control` being set.
See: https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html
> Disable ACLs on the S3 bucket and require object ownership
